#!/bin/bash

WD=$(dirname $0)

# parse DOCKER_TAG
DIST=$(echo $DOCKER_TAG | awk \
	'BEGIN{FS=OFS="-"}{NF=(NF>1?NF-1:NF); print}')
DPDK_VER="$(echo $DOCKER_TAG | awk \
	'BEGIN{FS=OFS="-"}{print $NF=="latest"?"master":$NF}')"

# default OS image
case $DIST in
	centos*)
		BASE=centos
		;;
	stretch*)
		BASE=debian
		;;
	*)
		BASE=ubuntu
		;;
esac

echo "Building from $DIST, DPDK version: $DPDK_VER"
echo "tag: $DOCKER_TAG"
echo "image_name: $IMAGE_NAME"
echo "dockerfile: $DOCKERFILE_PATH"
echo "pwd: $PWD"

# build dpdk on base:dist
docker run \
	-e DOCKER_UID=$UID \
	-e BASE=$BASE \
	-e DIST=$DIST \
	-e DPDK_VER=$DPDK_VER \
	-v $PWD/:/workdir \
	-w /workdir \
	--rm \
	${BASE}:${DIST} \
	/bin/bash -c "./scripts/pre-build.${BASE}.sh && \
	./scripts/build.dpdk.sh"
