#!/bin/bash

WD=$(dirname $0)

function my_exit {
	echo $1
	exit 1
}

# parse DOCKER_TAG
DIST=$(echo $DOCKER_TAG | awk 'BEGIN{FS=OFS="-"}{print $1}')
DPDK_VER=$(echo $DOCKER_TAG | awk 'BEGIN{FS=OFS="-"}{print $2}')
MACHINE=$(echo $DOCKER_TAG | awk 'BEGIN{FS=OFS="-"}{print $3}')

[ "x$DIST" = "x" ] && my_exit "No distribution specified"
[ "x$DPDK_VER" = "x" ] && my_exit "No DPDK version specified"
[ "x$MACHINE" = "x" ] && MACHINE="default"

[ "x$DPDK_URL" = "x" ] && my_exit "Specify DPDK_URL"

# default OS image
case $DIST in
	centos*)
		BASE=centos
		;;
	stretch*)
		BASE=debian
		;;
	*)
		BASE=ubuntu
		;;
esac

echo "Building from $DIST, DPDK version: $DPDK_VER"
echo "tag: $DOCKER_TAG"
echo "image_name: $IMAGE_NAME"
echo "dockerfile: $DOCKERFILE_PATH"
echo "pwd: $PWD"

# build dpdk on base:dist
docker run \
	-e DOCKER_UID=$UID \
	-e BASE=$BASE \
	-e MACHINE=$MACHINE \
	-e DIST=$DIST \
	-e DPDK_URL=$DPDK_URL \
	-e MESON_OPTS="$MESON_OPTS" \
	-e DPDK_VER=$DPDK_VER \
	-v $PWD/:/workdir \
	-w /workdir \
	--rm \
	${BASE}:${DIST} \
	/bin/bash -c "./scripts/pre-build.${BASE}.sh && \
	./scripts/build.dpdk.sh"
