name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push RL8
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile.rockylinux8
          push: true
          build-args: |
            DPDK_VERSION=v23.11
            MESON_OPTS=-Dcpu_instruction_set=generic
            GO_VER=1.21.4
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dpdk-rockylinux8:v23.11-go1.21.4-snf
      -
        name: Build and push RL9
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile.rockylinux9
          push: true
          build-args: |
            DPDK_VERSION=v23.11
            MESON_OPTS=-Dcpu_instruction_set=generic
            GO_VER=1.21.4
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dpdk-rockylinux9:v23.11-go1.21.4-snf
